### ISSUE TITLE
Doesn't compile on GHC 9.2.3

### ISSUE THREAD

**Issue by ysangkok** [iand675/hs-opentelemetry#17]
Attempting to use this compiler version results in errors similar to this:

```
[20 of 32] Compiling OpenTelemetry.Trace.Id ( src/OpenTelemetry/Trace/Id.hs, /home/janus/flipstone/hs-opentelemetry/api/dist-newstyle/build/x86_64-linux/ghc-9.2.3/hs-opentelemetry-api-0.0.3.3/build/OpenTelemetry/Trace/Id.o, /home/janus/flipstone/hs-opentelemetry/api/dist-newstyle/build/x86_64-linux/ghc-9.2.3/hs-opentelemetry-api-0.0.3.3/build/OpenTelemetry/Trace/Id.dyn_o )

src/OpenTelemetry/Trace/Id.hs:114:43: error:
    • Couldn't match expected type ‘Word#’ with actual type ‘Word8#’
    • In the first argument of ‘convertByte’, namely ‘w’
      In the expression: convertByte w
      In a pattern binding: !(# w1, w2 #) = convertByte w
    |
114 |           let !(# w1, w2 #) = convertByte w
    |                                           ^
```

It's curious that there is a stack file for 9.2, but I can't actually get it to compile. Is it supposed to work on the 9.2 series?

**Comment by iand675** [comment]
Hi, 9.2 is still in progress. Last I tried, there were some underlying dependencies that weren't compatible yet. I'll give it another go!

**Comment by iand675** [comment]
Hi! https://hackage.haskell.org/package/hs-opentelemetry-api-0.0.3.5 has been released, adding support for GHC 9.2.
