### PR TITLE
Build with template-haskell-2.17.0

### LINKED ISSUE #9: Cannot build with GHC 9
```
src/OpenTelemetry/Baggage.hs:84:27: error:
    • Couldn't match type ‘Q’ with ‘Code m’
      Expected: Code m Token
        Actual: Q (TExp a0)
    • In the expression: unsafeTExpCoerce $ bsToExp tok
      In an equation for ‘liftTyped’:
          liftTyped (Token tok) = unsafeTExpCoerce $ bsToExp tok
      In the instance declaration for ‘Lift Token’
    • Relevant bindings include
        liftTyped :: Token -> Code m Token
          (bound at src/OpenTelemetry/Baggage.hs:84:3)
   |
84 |   liftTyped (Token tok) = unsafeTExpCoerce $ bsToExp tok
   |    
```

### PR DESCRIPTION
**Pull request by ocharles**
Fixes #9

### CODE REVIEW

**Comment by iand675** [comment]
Thanks @ocharles, really appreciate the contribution.
